steps:
  # 1. Install dependencies in project root
  - name: 'gcr.io/cloud-builders/npm'
    dir: '.'
    args: ['install']

  # 2. Install dependencies in functions directory
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['install']

  # 3. Deploy Firebase services
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args:
      - 'deploy'
      - '--project=${_PROJECT_ID}'

  # 4. Run seed-database.js
  - name: 'gcr.io/cloud-builders/node'
    entrypoint: 'node'
    args: ['seed-database.js']

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
