steps:
  # 1. Install dependencies for the root project
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # 2. Install dependencies in the nested functions directory
  - name: 'node:20'
    entrypoint: npm
    dir: 'functions/functions'
    args: ['install']

  # 3. Deploy Firebase services (functions, rules, storage, hosting, auth, etc.)
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args:
      - 'deploy'
      - '--project=${_PROJECT_ID}'
      # Example: limit to specific services with --only
      # - '--only=hosting,firestore:rules,storage:rules,functions,auth'

  # 4. Run seed-database.js to populate Firestore
  - name: 'node:20'
    entrypoint: node
    args: ['seed-database.js']

timeout: 1200s # 20 minutes, adjust if seeding takes longer

options:
  logging: CLOUD_LOGGING_ONLY
